### PR TITLE
Fix 404 pages on fresh installation of the plugin

### PR DESCRIPTION
**Pull request by mostafa-hisham**
fix #[3146](https://github.com/Strategy11/awpcp/issues/3146)
I was enabled to reproduce the issue when I freshly installed the plugin.

In this area of the code
https://github.com/Strategy11/another-wordpress-classifieds-plugin/blob/ba83be6821f40f9c7a151b6d6ebb3499416d224a/includes/class-awpcp.php#L561-L567

The `flush_rewrite_rules` function was hooked to the "plugins_loaded" which happens on the plugin activation 
so it will not work after adding the custom post types in the `init` hook

https://github.com/Strategy11/another-wordpress-classifieds-plugin/blob/ba83be6821f40f9c7a151b6d6ebb3499416d224a/includes/class-awpcp.php#L138

Calling the `flush_rewrite_rules` function directly fixed the issue with me and the condition on the `awpcp-flush-rewrite-rules` option in this line will prevent it for running on each `init` event

https://github.com/Strategy11/another-wordpress-classifieds-plugin/blob/ba83be6821f40f9c7a151b6d6ebb3499416d224a/includes/class-awpcp.php#L561

### CODE REVIEW

**Comment by mostafa-hisham** [comment]
@stephywells 
I faced problems with unit testing. it is not added as a script in comopser.json 
when I tried to run them I got 138 failed tests from 297 most of the errors are `Call to undefined function`  like
_x(), wp_rand(), _n(), wp_parse_args(), esc_attr(),......
I ran the `install-wp-tests` command but it didn't help

Also, the vendor directory is added to the git repo I didn't push the changes in it after the composer install
I think it is better to add it in the .gitignore file and not push it.

**Review by stephywells — APPROVED** [review]
This looks great too! Thanks for cleaning up a bit too!

**Comment by stephywells** [comment]
> @stephywells I faced problems with unit testing. it is not added as a script in comopser.json when I tried to run them I got 138 failed tests from 297 most of the errors are `Call to undefined function` like _x(), wp_rand(), _n(), wp_parse_args(), esc_attr(),...... I ran the `install-wp-tests` command but it didn't help
> 
> Also, the vendor directory is added to the git repo I didn't push the changes in it after the composer install I think it is better to add it in the .gitignore file and not push it.

You're right that the vendor folder should be excluded, except for the composer autoloading that already in the repo.

The unit testing on this project hasn't been running well for a while. When we run them in GH using the "ready to merge" tag, there is a patchwork error https://github.com/Strategy11/another-wordpress-classifieds-plugin/actions/runs/4484949580/jobs/7885969046

If you still have time left, this would be really great to have fixed if it doesn't take too much time.

Thanks for paying attention to this and trying to run the tests!

**Review by garretlaxton — APPROVED** [review]
Nice, this works great!

**Pull request merged**
