### PR TITLE
More escaping

### PR DESCRIPTION
**Pull request by stephywells**
Things to test:
This PR affects pretty much the whole plugin. It would be great to test all the admin pages, and frontend features list creating a listing, renewing, editing...

### CODE REVIEW

**Comment by garretlaxton** [comment]
Sorry, didn't see this. I will take a look at this tonight and tomorrow.

**Comment by garretlaxton** [comment]
I am seeing this database error which is preventing me from creating ads in the backend

```
WordPress database error: [Unknown column '*' in 'field list']
SELECT `*`, CASE rec_increment WHEN 'D' THEN 1 WHEN 'W' THEN 2 WHEN 'M' THEN 3 WHEN 'Y' THEN 4 END AS _duration_interval FROM `wp_awpcp_adfees` WHERE 1 = 1 ORDER BY `_duration_interval ASC, rec_period ASC, adterm_name` ASC
```

**Comment by stephywells** [comment]
Thank you @garretlaxton ! This is fixed now.

**Comment by garretlaxton** [comment]
I am seeing one more DB error.

```
WordPress database error: [Unknown column '_duration_interval ASC, rec_period ASC, adterm_name' in 'order clause']
SELECT *, CASE rec_increment WHEN 'D' THEN 1 WHEN 'W' THEN 2 WHEN 'M' THEN 3 WHEN 'Y' THEN 4 END AS _duration_interval FROM `wp_awpcp_adfees` WHERE 1 = 1 ORDER BY `_duration_interval ASC, rec_period ASC, adterm_name` ASC
```

**Comment by stephywells** [comment]
Thanks for the great catch @garretlaxton ! This has been fixed now along with one other spot where this was happening.

**Comment by garretlaxton** [comment]
I can't select a payment term when adding a listing in the backend.
image

I don't see any of the buttons on the homepage.
image

But they show when I go back to 4.3.1.
image

**Comment by stephywells** [comment]
Thanks so much for all the testing @garretlaxton ! I'm having trouble replicating these ones.

> I can't select a payment term when adding a listing in the backend.

What happens when you click the "edit" link for the plan? Do you see any js errors?

> I don't see any of the buttons on the homepage.

I'm not seeing this one either. Any suggestions on what I can try?

**Comment by garretlaxton** [comment]
When I click the edit button to add a payment term it doesn't do anything. I do see that the console says the JS isn't found, but I looked and all the files are there.
image

**Comment by stephywells** [comment]
Thank you! I found the issue with js files not loading right when not working with the build scripts and with script debug off. Does that solve the problem for you?

**Comment by garretlaxton** [comment]
That worked great!

I'm not sure why the buttons don't show on the main classifieds page, but they show when I click on an ad. I can give you access if you want it. 
https://grunge.us.eu.org/classifieds/

I am also seeing the ad image show at the top of the page.
image

**Comment by garretlaxton** [comment]
I found out how to replicate the image issue. 

- Create an ad with 2 images
- Edit the ad on the front end and change the primary image
image
- Save the ad and view the ad

It's adding the image to the featured image section.
image

**Comment by stephywells** [comment]
I'm seeing the image added as the featured image, but it's not showing an extra time on the page for me. I tried your steps, but I'm still not seeing the image at the top like on your page. I'll keep looking to see if I can find something.

**Comment by stephywells** [comment]
@garretlaxton does this image work differently for you in the previous version?

**Comment by stephywells** [comment]
Nevermind! I see it now in the 2024 theme.

**Pull request merged**
